# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='my_field',
            field=models.IntegerField(default=0),
        ),
    ]
