# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_recipe_my_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='checked',
            field=models.BooleanField(default=True),
        ),
    ]
