# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_amount',
            field=models.IntegerField(default=0),
        ),
    ]
