# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_recipe_recipe_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_show',
            field=models.BooleanField(default=True),
        ),
    ]
