# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_ingredient_ingredient_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Recipe'),
        ),
    ]
