# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_ingredient_ingredient_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
