# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20171203_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_quantity',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
