# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 00:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20171122_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
