# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20171025_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
