# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_ingredient_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='quantity_type',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_quantity',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
